Actualizo todo el .yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,9 +18,15 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '22'
-          
-      - name: Debug environment variables
-        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
+
+      - name: Check if secret exists (for debug)
+        run: |
+          if [ -z "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" ]; then
+            echo "Secret GOOGLE_APPLICATION_CREDENTIALS is missing!"
+            exit 1
+          else
+            echo "Secret GOOGLE_APPLICATION_CREDENTIALS is available."
+          fi
 
       - name: Install Dependencies
         run: npm install
@@ -30,6 +36,16 @@ jobs:
 
       - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
         run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > "${{ github.workspace }}/firebase-key.json"
+
+      # For debugging: check if the file was created
+      - name: Check if Firebase key file exists
+        run: |
+          if [ -f "${{ github.workspace }}/firebase-key.json" ]; then
+            echo "Firebase key file created successfully."
+          else
+            echo "Firebase key file not found."
+            exit 1
+          fi
 
       - name: Build Project
         run: npm run build
